### PR TITLE
Uploaded Fabian Levican's lab 3

### PR DESCRIPTION
**Pull request by iZafiro**
Lab 3: https://colab.research.google.com/drive/1oSSRMqztKC5_U6xNJkFBp4C37fs-1uUo

### CODE REVIEW

**Comment by iZafiro** [comment]
Lab 4: https://colab.research.google.com/drive/1rKUCOJ_OPt0kz0L09I3FKj4sMlMPTRmw

**Comment by ajlace** [comment]
Lab 3 looks good.

**Comment by iZafiro** [comment]
Lab 5: https://colab.research.google.com/drive/1OqrnCEeYXsuWu3QCgsHyaW3N5pizzCjD

**Review by ajlace — CHANGES_REQUESTED** [review]
Lab 4: Plots are insufficient. I should not need to read your code to understand what the plots show. Hence you need to include labels, split the convergence and accuracy plots, use a log-log plot for the convergence, and properly display a plot of exact solution vs approximation.

The 2D graph is also unclear for the same reasons. Also include the exact solution in the 2D plot as it otherwise doesn't show much.

**Review by ajlace — CHANGES_REQUESTED** [review]
Lab 5: While the implementations look correct, the plots make it very hard to confirm the convergence. Please clarify the plots using different colors for the different functions that exist within the same plot or describe more clearly what is showing.

See my comment about lab 4 as well.

**Comment by iZafiro** [comment]
Lab 2: https://colab.research.google.com/drive/1auv7RU5asMryrwHCzmjsQILKi4Ciunoy

**Comment by iZafiro** [comment]
Lab 6: https://colab.research.google.com/drive/1hDAO9GCI_8oGOn0uRbmcQMNxhtTNP4Kc

**Comment by iZafiro** [comment]
Lab 7: https://colab.research.google.com/drive/1YyIeivo5QQhaFw05eGcTgdW6R1swW2Co

**Comment by iZafiro** [comment]
@ajlace Hi! I think I made all the requested changes. In lab 4 I also changed the exponents of x and y from 2 to 3 in the last test to make the plot fit better. In lab 5 I added labels and changed the plot style, so it should be easier to trace the plots to their explanation in the text cell above each test. As you can see in the diffs, I didn't alter the functionality of anything else. The changes can also be seen using the Google colab links. Thanks!

**Comment by ajlace** [comment]
@iZafiro The plots in both lab 4 and lab 5 look great now! Good job  🙂

**Comment by ajlace** [comment]
Lab 6 also looks great.

**Comment by ajlace** [comment]
Lab 7 is also done!

**Review by ajlace — APPROVED** [review]

**Pull request merged**
