### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by timaslj**
Done!

### CODE REVIEW

**Review by ajlace — CHANGES_REQUESTED** [review]
Looks great, try to include a link to a Google Collab file (see template at the master branch) so that we also can run your code.

Before approving I would need you to confirm that both Github accounts (timmitommi and timaslj) that have worked on this lab are yours.

**Comment by timaslj** [comment]
For some reason I was logged into my old github account timmitommi when I worked on the lab. Both accounts are indeed mine. Is this enough or can I confirm it another way?

**Comment by timaslj** [comment]
Lab3 is in this PR as well. Is it better to make a new branch for each lab?

**Comment by ajlace** [comment]
The confirmation is enough! It would be preferable if you keep each lab on its own branch, however if you have already uploaded lab 3 here that is fine!

**Review by ajlace — APPROVED** [review]

**Pull request merged**
