### PR TITLE
Lindevanbeers

### PR DESCRIPTION
**Pull request by LindeBee**
Lab 3 submission

### CODE REVIEW

**Comment by LindeBee** [comment]
I also updated lab 2 according to the feedback from Ajla

**Comment by LindeBee** [comment]
Lab 4 is added too

**Comment by ajlace** [comment]
Both Lab 2 and 3 are now done. Great inclusion of plots in lab 3!

**Comment by LindeBee** [comment]
Lab 5 added

**Comment by ajlace** [comment]
Lab 4 looks great!

**Comment by ajlace** [comment]
Lab 5 looks great!

**Comment by LindeBee** [comment]
Lab 6 added

**Comment by ajlace** [comment]
Lab 6 looks great!

**Comment by ajlace** [comment]
Lab 7 looks good as well!

**Review by ajlace — APPROVED** [review]

**Pull request merged**
